from .schemas import BillManagerBulkInvoiceRequest as BillManagerBulkInvoiceRequest, BillManagerBulkInvoiceResponse as BillManagerBulkInvoiceResponse, BillManagerCancelBulkInvoiceRequest as BillManagerCancelBulkInvoiceRequest, BillManagerCancelInvoiceResponse as BillManagerCancelInvoiceResponse, BillManagerCancelSingleInvoiceRequest as BillManagerCancelSingleInvoiceRequest, BillManagerOptInRequest as BillManagerOptInRequest, BillManagerOptInResponse as BillManagerOptInResponse, BillManagerSingleInvoiceRequest as BillManagerSingleInvoiceRequest, BillManagerSingleInvoiceResponse as BillManagerSingleInvoiceResponse, BillManagerUpdateOptInRequest as BillManagerUpdateOptInRequest, BillManagerUpdateOptInResponse as BillManagerUpdateOptInResponse
from _typeshed import Incomplete
from mpesakit.auth import TokenManager as TokenManager
from mpesakit.http_client import HttpClient as HttpClient
from pydantic import BaseModel

class BillManager(BaseModel):
    http_client: HttpClient
    token_manager: TokenManager
    app_key: str | None
    model_config: Incomplete
    def opt_in(self, request: BillManagerOptInRequest) -> BillManagerOptInResponse: ...
    def update_opt_in(self, request: BillManagerUpdateOptInRequest) -> BillManagerUpdateOptInResponse: ...
    def send_single_invoice(self, request: BillManagerSingleInvoiceRequest) -> BillManagerSingleInvoiceResponse: ...
    def send_bulk_invoice(self, request: BillManagerBulkInvoiceRequest) -> BillManagerBulkInvoiceResponse: ...
    def cancel_single_invoice(self, request: BillManagerCancelSingleInvoiceRequest) -> BillManagerCancelInvoiceResponse: ...
    def cancel_bulk_invoice(self, request: BillManagerCancelBulkInvoiceRequest) -> BillManagerCancelInvoiceResponse: ...
